Fixing Issue #14 : sending MDX query and receiving query Plan
tibo-mllr/activeviam-projet pull request #18
Opened 2024-11-10 13:25 UTC by AlexandreCGithub

This feature adds a page to send an MDX query to the server and receive a JSON query plan as described in issue #14

2024-11-10 15:50 UTC, tibo-mllr commented
Beaucoup de pipeline de fail, il faut activer le "Format on save" (déjà fait dans le '.vscode/settings.json' et avoir les bonnes extensions, comme ça pas de problème

2024-11-10 16:02 UTC, tibo-mllr requested changes
Apart from the specific comments I made, maybe for components use èxport default function` instead of using a const and exporting later.
That's how it was done before if you look at the files. And that was made directly by Next developers, so maybe that's a good thing to keep it the same.

For the type, I see you use FC. That's not what was used before, but as you want

2024-11-10 16:03 UTC, tibo-mllr commented
On doit aussi attendre que @TimotheeVrg merge sa PR avant de merge celle-ci, sinon ça va pas le faire.

2024-11-10 16:35 UTC, tibo-mllr commented on app/page.tsx
Maybe we can also remove this page a default to the other one.
In which case you need to add the following to the `next.config.mjs`:
```ts
async redirects() {
  return [
    {
      source: '/',
      destination: '/submitQuery',
      permanent: true,
    },
  ];
},
```

2024-11-11 01:09 UTC, AlexandreCGithub commented on app/page.tsx
Made submitQuery default, didn't delete the main page for now, maybe it could be useful

2024-11-11 15:03 UTC, AlexandreCGithub commented on app/submitQuery/page.tsx
> +              <div>
Simplified to avoid using div, so the problem is resolved for now

2024-11-11 15:03 UTC, AlexandreCGithub commented on app/submitQuery/page.tsx
> +                <label
Simplified to avoid using label, so the problem is resolved for now

2024-11-11 15:06 UTC, tibo-mllr commented on app/page.tsx
But this page will be useless then... Which is contrary to thr work Timothée did by removing useless files. We can remove it.

2024-11-11 15:07 UTC, tibo-mllr commented on app/submitQuery/page.tsx
> +              <div>
Nevermind, Form.Group is from Bootstrap, I was wrong here

2024-11-11 15:09 UTC, tibo-mllr commented on app/submitQuery/page.tsx
> +const DEFAULT_URL =
Love this !

2024-11-11 15:11 UTC, tibo-mllr commented on app/page.tsx
~~+ the button that's inside is not a real button as there's no `onClick` attribute~~

2024-11-11 15:29 UTC, AlexandreCGithub commented on app/page.tsx
Removed

2024-11-11 15:34 UTC, merged