Fixing issue #40 : creating the summary page
tibo-mllr/activeviam-projet pull request #44
Opened 2024-12-06 14:12 UTC by AlexandreCGithub

# Issue Number:

Fix issue #40 

# Description:

Creating a summary page with query plan information

# How to test:

Launch the app
Go to localhost:3000/summary
Check that the page exists and is working

# Other notes:

2024-12-12 09:28 UTC, tibo-mllr requested changes

2024-12-12 09:28 UTC, tibo-mllr commented on app/summary/page.tsx
> +  console.log(queryPlan);
Please remove

2024-12-12 09:28 UTC, tibo-mllr commented on app/summary/page.tsx
> +  return (
Instead of
```typescript
if (thing)
    return <loooooong........... normal thing>
return <something else>
```
rather put it like
```typescript
if (!thing)
    return <something short>
return <the true loooooong thing>
```
for readability

2024-12-12 09:28 UTC, tibo-mllr commented on app/summary/page.tsx
> +    for (let i = 0; i < SelectPass_0.aggregateRetrievals.length; i++) {
Instead of always writing `SelectPass_0.aggregateRetrievals` and `SelectPass_0.databaseRetrievals`, define them before with something like `const { aggregateRetrievals, databseRetrievals } = SelectPass_0`

2024-12-12 09:28 UTC, tibo-mllr commented on app/summary/page.tsx
> +    const [SelectPass_0] = queryPlan;
Mix between PascalCase and snake_case, while typescript usually use camelCase.
Maybe call it something like `selectPass0` or `firstSelectPass`

2024-12-12 09:31 UTC, AlexandreCGithub commented
I will work on the requested changes + implement some new features before merge

2024-12-12 22:00 UTC, AlexandreCGithub commented
User can now select the wanted query plan if there is several parts

2024-12-14 16:36 UTC, tibo-mllr approved these changes

2024-12-14 18:53 UTC, merged