Fix issue #41: 10 slowest nodes
tibo-mllr/activeviam-projet pull request #52
Opened 2024-12-19 08:48 UTC by TimotheeVrg

# Issue Number:

Fix issue #41  

# Description:

Add a page to visualize the slowest nodes
you can choose a query plan pass and the number of nodes you wan to see

# How to test:

Launch the app.
Go to the "Nodes" page.
Try to change the pass and the number of nodes
(No added dependency)

2024-12-19 10:26 UTC, tibo-mllr requested changes

2024-12-19 10:26 UTC, tibo-mllr commented on app/nodes/page.tsx
> +        {`Top ${numberOfNodes} Slowest Nodes`}
I think you can simply do `<Typography ...>Top {numberOfNodes} slowest nodes</...>` (without the backticks)

2024-12-19 10:26 UTC, tibo-mllr commented on lib/functions/slowestNodes.ts
> +  const startTimes: number[] = timingInfo["startTime"];
`timingInfo.startTime` or directly, for both `const { startTime: startTimes, elapsedTime: elapsedTimes } = timingInfo`

2024-12-19 10:26 UTC, tibo-mllr commented on lib/functions/slowestNodes.ts
> +  const endTimes: number[] = startTimes.map(function (num, idx) {
`.map((num, idx) => (num + elapsedTimes[idx]))`

2024-12-19 10:26 UTC, tibo-mllr commented on lib/functions/slowestNodes.ts
> +    startTimes.reduce((a, b) => Math.min(a, b))
Normally the start times are already sorted, so it should be the first one

2024-12-19 10:26 UTC, tibo-mllr commented on lib/functions/slowestNodes.ts
> +    (node: AggregateRetrieval) => ({
Don't need to specify the type of `node` here if you already have the type of `aggregateRetrievals`

2025-01-06 17:17 UTC, TimotheeVrg commented on app/nodes/page.tsx
> +        {`Top ${numberOfNodes} Slowest Nodes`}
Indeed you're right

2025-01-06 17:17 UTC, TimotheeVrg commented on lib/functions/slowestNodes.ts
> +  const endTimes: number[] = startTimes.map(function (num, idx) {
yes that's better written

2025-01-06 17:19 UTC, TimotheeVrg commented on lib/functions/slowestNodes.ts
> +    (node: AggregateRetrieval) => ({
👍

2025-01-07 13:21 UTC, tibo-mllr approved these changes

2025-01-07 17:49 UTC, merged